name: clase_1
description: Bases del lenguaje Dart.
version: 1.0.0
repository: https://github.com/Bagboy16/clase_1

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
